#!/bin/bash

set -o errexit
set -o pipefail
readonly GOPATH="${GOPATH%%:*}"

main() {
  _cd_into_top_level "$@"
  _generate_coverage_files "$@"
  _combine_coverage_reports "$@"
  exit $fail
}

_cd_into_top_level() {
  cd "$(git rev-parse --show-toplevel)"
}

_generate_coverage_files() {
  for dir in $(find . -maxdepth 10 -not -path './.git*' -not -path '*/_*' -type d); do
    if ls $dir/*.go &>/dev/null ; then
      go test -race "$@" -coverprofile=$dir/profile.coverprofile $dir | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' || fail=1 
    fi
  done
}

_install_gover() {
  if [[ ! -x "${GOPATH}/bin/gover" ]] ; then
    go get -u github.com/modocache/gover
  fi
}

_combine_coverage_reports() {
  _install_gover
  ${GOPATH}/bin/gover
}

main "$@"
