#!/bin/bash
set -e

readonly GOPATH="${GOPATH%%:*}"
files=$(git ls-files '*.go' | grep -v 'vendor/*')

main() {
  check_fmt
  check_lint
}

check_fmt() {
  for file in $files ; do
    gofmt $file | diff -u $file -
  done
}

check_lint() {
  _install_linter

  for package in $(go list ./... | grep -v '/vendor/') ; do
    lint=$(${GOPATH}/bin/golint $package 2>&1)
    if [[ ! "$lint" =~ ^[[:blank:]]*$ ]] ; then
      echo "$lint" && exit 1
    fi
  done
}

_install_linter() {
  if [[ ! -x "${GOPATH}/bin/golint" ]] ; then
    go get -u github.com/golang/lint/golint
  fi
}

main "$@"
